"""Training loop layer (Day 27): episode schedule, checkpoints, budget guard.

PLAN line 273 only. No execution cache (COMP-EXP-11), no experiment
orchestrator (COMP-EXP-12), no resume/warm start, no DQN/PPO/replay buffer,
no second Spark runner, no reward or T_ref recomputation.

A training run records machinery execution only; it supports no claim of
learning, convergence, improvement or superiority.
"""
from sparkrl.training.ablation import (  # noqa: F401
    ABLATION_EPISODES_PER_SEED,
    ABLATION_EPOCHS,
    ABLATION_SEEDS,
    ABLATION_TRAIN_CELLS,
    EXP007_ID,
    combined_planned,
    exp007_budget_summary,
    planned_executions,
    sc6_headroom,
    sc6_remaining,
)
from sparkrl.training.exp008 import (  # noqa: F401
    A3_ARMS,
    A4_ACTION_MODE,
    A4_ACTION_SUBSET,
    A4_ARMS,
    ALL_ARMS,
    ARM_A3_R3,
    ARM_A3_R4_LOG_RATIO,
    ARM_A3_TIME_ONLY,
    ARM_A4_MODE4,
    A5_STATUS,
    CONFIG_SCHEMA,
    EXECUTION_AUTHORIZATION,
    EXECUTION_AUTHORIZED,
    EXP008_ID,
    A5DisabledError,
    Exp008ArmConfig,
    Exp008ConfigError,
    Exp008Error,
    Exp008IncompleteError,
    Exp008Q0Error,
    Exp008ScopeError,
    a4_action_configurations,
    all_arm_configs,
    arm_config_from_mapping,
    arm_config_from_yaml,
    arm_scope_summary,
    build_reward_calculator,
    guard_a5,
    guard_action,
    guard_agent_seeds,
    guard_cell,
    guard_metrics,
    guard_q0_for_mode,
    guard_q0_projection,
    guard_q0_rows,
    guard_q0_source,
    guard_split,
    load_exp008_config,
    q0_policy,
    required_fields,
)
from sparkrl.training.loop import (  # noqa: F401
    CHECKPOINT_EVERY_EPISODES,
    EARLY_STOP_STABLE_EPOCHS,
    EPISODE_SCHEMA,
    EPOCH_DEFINITION,
    LOOP_VERSION,
    MANIFEST_SCHEMA,
    BudgetPlanError,
    Cell,
    Episode,
    EpisodeOutcome,
    RunDirExistsError,
    TrainingConfig,
    TrainingPlan,
    TrainingPlanError,
    TrainingResult,
    build_env_and_agent,
    build_plan,
    greedy_snapshot,
    plan_episodes,
    run_training,
)
